source 'https://gems.ruby-china.com'

# Specify your gem's dependencies in cocoapods-xcremotecache.gemspec
gemspec

# Keep bundle gems equal to xcode project, for convenience to debug plugin.
# gem 'cocoapods', :path => '~/dev-gems/Cocoapods'
